server:
  port: 8489

management:
  endpoints:
    web:
      base-path: /

testing-support.enabled: ${TESTING_SUPPORT_ENABLED:}

ttlInSeconds: ${TTLINSECONDS:14400}

rs256:
  enabled: ${RS256_ENABLED:false}
  privateKey: ${RS256_PRIVATEKEY:}
  publicKey: ${RS256_PUBLICKEY:}

spring:
  application:
    name: Service Auth Provider
