server:
  port: 8489

management:
  endpoints:
    web:
      base-path: /

testing-support.enabled: ${TESTING_SUPPORT_ENABLED:}

jwtKey: ${JWTKEY:wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==}

ttlInSeconds: ${TTLINSECONDS:14400}

rs256:
  enabled: ${RS256_ENABLED:false}
  privateKey: ${RS256_PRIVATEKEY:}
  publicKey: ${RS256_PUBLICKEY:}

spring:
  application:
    name: Service Auth Provider
