server:
  port: 8489

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
testing-support.enabled: ${TESTING_SUPPORT_ENABLED:}
jwtKey: ${JWTKEY:wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==}

ttlInSeconds: ${TTLINSECONDS:14400}

rs256:
  enabled: ${RS256_ENABLED:false}
  privateKey: ${RS256_PRIVATEKEY:}
  publicKey: ${RS256_PUBLICKEY:}

spring:
  application:
    name: Service Auth Provider
  cloud:
    propertiesvolume:
      paths: /mnt/secrets/s2s
      aliases:
        s2s.microservicekey-cmcLegalFrontend: MICROSERVICEKEYS_CMC_LEGAL_FRONTEND
        s2s.microservicekey-cmcClaimStore: MICROSERVICEKEYS_CMC_CLAIM_STORE
        s2s.microservicekey-divorce: MICROSERVICEKEYS_DIVORCE
        s2s.microservicekey-divorce-frontend: MICROSERVICEKEYS_DIVORCE_FRONTEND
        s2s.microservicekey-divorceCcdSubmission: MICROSERVICEKEYS_DIVORCE_CCD_SUBMISSION
        s2s.microservicekey-divorceCcdValidation: MICROSERVICEKEYS_DIVORCE_CCD_VALIDATION
        s2s.microservicekey-divorceDocumentUpload: MICROSERVICEKEYS_DIVORCE_DOCUMENT_UPLOAD
        s2s.microservicekey-divorceDocumentGenerator: MICROSERVICEKEYS_DIVORCE_DOCUMENT_GENERATOR
        s2s.microservicekey-draftStoreTests: MICROSERVICEKEYS_DRAFT_STORE_TESTS
        s2s.microservicekey-platformJobScheduler: MICROSERVICEKEYS_JOBSCHEDULER
        s2s.microservicekey-reference: MICROSERVICEKEYS_REFERENCE
        s2s.microservicekey-sscs: MICROSERVICEKEYS_SSCS
        s2s.microservicekey-sscs-bulkscan: MICROSERVICEKEYS_SSCS_BULKSCAN
        s2s.microservicekey-sscs-tribunals-case: MICROSERVICEKEYS_SSCS_TRIBUNALS_CASE
        s2s.microservicekey-probate-frontend: MICROSERVICEKEYS_PROBATE_FRONTEND
        s2s.microservicekey-probate-backend: MICROSERVICEKEYS_PROBATE_BACKEND
        s2s.microservicekey-send-letter-consumer: MICROSERVICEKEYS_SEND_LETTER_CONSUMER
        s2s.microservicekey-send-letter-tests: MICROSERVICEKEYS_SEND_LETTER_TESTS
        s2s.microservicekey-em-gw: MICROSERVICEKEYS_EM_GW
        s2s.microservicekey-finrem-document-generator: MICROSERVICEKEYS_FINREM_DOCUMENT_GENERATOR
        s2s.microservicekey-finrem-notification-service: MICROSERVICEKEYS_FINREM_NOTIFICATION_SERVICE
        s2s.microservicekey-finrem-case-orchestration: MICROSERVICEKEYS_FINREM_CASE_ORCHESTRATION
        s2s.microservicekey-finrem-payment-service: MICROSERVICEKEYS_FINREM_PAYMENT_SERVICE
        s2s.microservicekey-finrem-ccd-data-migrator: MICROSERVICEKEYS_FINREM_CCD_DATA_MIGRATOR
        s2s.microservicekey-jui-webapp: MICROSERVICEKEYS_JUI_WEBAPP
        s2s.microservicekey-pui-webapp: MICROSERVICEKEYS_PUI_WEBAPP
        s2s.microservicekey-coh-cor: MICROSERVICEKEYS_COH_COR
        s2s.microservicekey-bulk-scan-processor: MICROSERVICEKEYS_BULK_SCAN_PROCESSOR
        s2s.microservicekey-bulk-scan-processor-tests: MICROSERVICEKEYS_BULK_SCAN_PROCESSOR_TESTS
        s2s.microservicekey-bulk-scan-orchestrator: MICROSERVICEKEYS_BULK_SCAN_ORCHESTRATOR
        s2s.microservicekey-bar-api: MICROSERVICEKEYS_BAR_API
        s2s.microservicekey-api-gw: MICROSERVICEKEYS_API_GW
        s2s.microservicekey-em-annotation-app: MICROSERVICEKEYS_EM_ANNOTATION_APP
        s2s.microservicekey-em-npa-app: MICROSERVICEKEYS_EM_NPA_APP
        s2s.microservicekey-cet: MICROSERVICEKEYS_CET
        s2s.microservicekey-cet-frontend: MICROSERVICEKEYS_CET_FRONTEND
        s2s.microservicekey-fpl-case-service: MICROSERVICEKEYS_FPL_CASE_SERVICE
        s2s.microservicekey-iac: MICROSERVICEKEYS_IAC
        s2s.microservicekey-em-stitching-api: MICROSERVICEKEYS_EM_STITCHING_API
        s2s.microservicekey-em-ccd-orchestrator: MICROSERVICEKEYS_EM_CCD_ORCHESTRATOR
        s2s.microservicekey-ccpay-bubble: MICROSERVICEKEYS_CCPAY_BUBBLE
        s2s.microservicekey-dg-template-management: MICROSERVICEKEYS_DG_TEMPLATE_MANAGEMENT_API
        s2s.microservicekey-dg-docassembly-api: MICROSERVICEKEYS_DG_DOCASSEMBLY_API
